### ISSUE TITLE
远程协助应用，点击主菜单中关于与开源软件，页面呈现透明状态

### ISSUE THREAD

**Issue by myk1343** [linuxdeepin/dtk#100]
### SUMMARY | 问题概要

[前置条件]
已安装华为线1050U5E系统

[步骤]
1. 启动远程协助，点击主菜单中关于，同时再点击开源软件

[结果]
1. 关于与开源软件，页面呈现透明状态 ，注：专业版本1050U5, 1060 也存在此问题

### DTK and OS VERSIONS | DTK&系统版本信息

华为线1050U5E
专业版本1050U5, 1060 wayland环境

### Minimal Reproducible Case Code | 最小复现案例代码

远程协助在main函数中用了此函数DApplication::loadDXcbPlugin(); 

### OBSERVED RESULT | 观察到的结果

远程协助应用，点击主菜单中关于与开源软件，页面呈现透明状态

### EXPECTED RESULT | 期望的结果

关于与开源软件，页面无透明状态

### ADDITIONAL INFORMATION | 额外补充

https://pms.uniontech.com/bug-view-208303.html

**Comment by kegechen** [comment]
see https://github.com/linuxdeepin/dtkwidget/issues/358

**Comment by kegechen** [comment]
fixed
