### ISSUE TITLE
dtkcore chinese2pinyin polyphonic support have duplicated results

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/dtk#109]
### SUMMARY | 问题概要

dtkcore `Dtk::Core::pinyin("", Dtk::Core::TS_NoneTone)` 返回结果可能包含完全相同的结果。例如 `Dtk::Core::pinyin("菠萝看图", Dtk::Core::TS_NoneTone)` 将返回两个 "boluokantu"，“用户反馈控制台” 将返回两个 "yonghufankuikongzhitai"。

### DTK and OS VERSIONS | DTK&系统版本信息

dtkcore 5.6.10
archlinux rolling

### Minimal Reproducible Case Code | 最小复现案例代码

`qDebug() << Dtk::Core::pinyin("菠萝看图", Dtk::Core::TS_NoneTone);`

### OBSERVED RESULT | 观察到的结果

`("boluokantu", "boluokantu")`

### EXPECTED RESULT | 期望的结果

`("boluokantu")`

**Comment by kegechen** [comment]
加上tone看看。
```sh
ch2py -s tones 菠萝看图
bōluókàntú
bōluókāntú
total size: 2

ch2py -s tones 用户反馈控制台        
yònghùfǎnkuìkòngzhìtái
yònghùfǎnkuìkòngzhìtāi
```
看： k**à**n k**ā**n
台：t**á**i t**ā**i

在 NoneTone 时确实应该再去一下重

**Comment by kegechen** [comment]
@BLumia merged
