### ISSUE TITLE
dtkdeclarative: 非 DDE 下，菜单首次显示时，菜单大小不正确

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/dtk#115]
### SUMMARY | 问题概要

dtkdeclarative: 非 DDE 下，菜单首次显示时，菜单大小不正确。

### DTK and OS VERSIONS | DTK&系统版本信息

发行版：Archlinux testing（无需 testing 即可复现）
桌面环境：KDE Plasma 5
dtkdeclarative 版本：5.6.15（注，当前 arch 仓库并非此版本，我是手动改 PKGBUILD 构建的此 tag 对应的版本。仓库中的版本比此版本老，且也存在此问题）

### Minimal Reproducible Case Code | 最小复现案例代码

``` qml
import QtQuick 2.15
import QtQml.Models 2.15
import QtQuick.Layouts 1.15
import QtQuick.Controls 2.15
import QtQuick.Window 2.15
import org.deepin.dtk 1.0

ApplicationWindow {
    title: activeFocusItem + " " + (activeFocusItem ? activeFocusItem.Accessible.name : "")
    width: 780
    height: 600
    visible: true

    RowLayout {
        anchors.fill: parent
        anchors.margins: 10

        spacing: 10

        ColumnLayout {
            Layout.fillWidth: true
            Layout.fillHeight: true

            Button {
                text: "按钮"
                onClicked: {
                    menu.open()
                }
            }

            Menu {
                id: menu
                header: SearchEdit {
                    placeholder: qsTr("搜索")
                }

                Instantiator {
                    asynchronous: true
                    model: [
                        "等距更纱黑体 SCa",
                        "更纱黑体 SC",
                        "方正黑体_GBK",
                        "方正魏碑_GBK",
                        "方正隶书_GBK",
                        "方正行楷_GBK",
                        "方正细黑一_GBK",
                        "方正楷体_GBK",
                    ]
                    delegate: MenuItem { }
                    onObjectAdded: {
                        object.text = model[index]
                        object.font.family = object.text
                        menu.insertItem(index, object)
                    }
                }
            }
        }
    }
}
```

然后 `qml filename.qml`，并点击里面的按钮，观察弹出的菜单大小。

### OBSERVED RESULT | 观察到的结果

菜单尺寸不正确，只显示了 header 和下面的一小部分空白：

![image](https://github.com/linuxdeepin/dtk/assets/10095765/3fd987b2-705d-451b-a35a-4b2329fada54)

![image](https://github.com/linuxdeepin/dtk/assets/10095765/b67bddc4-b43f-4b27-a5ac-be8f742746be)

### EXPECTED RESULT | 期望的结果

正常尺寸，与 dtk exhibition 显示效果一致。

### ADDITIONAL INFORMATION | 额外补充

示例代码基本是 dtk exhibition 中的例子复制粘贴修改而来的，此例子就有问题，而 dtk exhibition 里是正常的。

在 deepin v23 develop 仓库中的版本并无尺寸问题，但有一些别的较小的问题。

此问题在 @Decodetalkers 的设备上也可以复现。

**Comment by 18202781743** [comment]
与此问题应该类似 https://github.com/linuxdeepin/dtk/issues/98

**Comment by 18202781743** [comment]
现在已经规避此问题，功能在 https://github.com/linuxdeepin/dtk/issues/70  中完成
