### ISSUE TITLE
【deepin_V23_beta2】【一般】【有空】【发散测试】【终端】中文环境下'高级设置'-'光标'选项中允许Ctrl+滚轮缩放文本大小命令展示为英文

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/dtk#123]
### SUMMARY | 问题概要

必现问题

### DTK and OS VERSIONS | DTK&系统版本信息

镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
内核信息: Linux test-PC 6.1.32-amd64-desktop-hwe linuxdeepin/developer-center#23 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux

终端:6.0.6

### PRE-REQUIREMENT | 预置条件

中文环境下打开终端

### STEPS TO REPRODUCE | 复现步骤

进入终端-设置-高级设置-光标，观察允许Ctrl+滚轮缩放文本大小命令的展示效果

### OBSERVED RESULT | 观察到的结果

中文环境下，允许Ctrl+滚轮缩放文本大小命令展示的为英文

![截图_选择区域_20230831131924](https://github.com/linuxdeepin/dtk/assets/62528742/16d66667-ff38-43df-848c-048d7777ab11)

### EXPECTED RESULT | 期望的结果

展示为中文

**Comment by ArchieMeng** [comment]
https://github.com/linuxdeepin/deepin-terminal/pull/290
https://github.com/linuxdeepin/developer-center/issues/3848
重复问题。

**Comment by xuqi27837288** [comment]
已确认为重复问题，该问题单已重复问题关闭处理~
