### ISSUE TITLE
DDesktopService 应当位于 dtkgui 模块下

### ISSUE THREAD

**Issue by BLumia** [linuxdeepin/dtk#134]
### SUMMARY | 问题概要

DDesktopService 目前位于 dtkwidget 模块下，而不是 dtkgui 模块下。

### DTK and OS VERSIONS | DTK&系统版本信息

系统版本不相关。
dtk版本：5.6.16 （当前 master 版本也存在问题）

### Minimal Reproducible Case Code | 最小复现案例代码

不相关

**Comment by kegechen** [comment]
dtkwidget 中的标记废弃，标注使用dtkgui中的版本。实际实现调用dtkgui中的版本。
在 dtkgui 中增加 DDesktopServices 头文件
修改namespace, 防止出现同时引用出现冲突

**Comment by kegechen** [comment]
5.6.20 合并
