### ISSUE TITLE
DDialog接口问题

### ISSUE THREAD

**Issue by lengzhou321** [linuxdeepin/dtk#146]
### SUMMARY | 问题概要

ddialog的clearButtons如果在exec之前调用会出现问题，在之后调用是正常的。

### DTK and OS VERSIONS | DTK&系统版本信息

桌面专业版：
MajorVersion=20
MinorVersion=1050
OsBuild=11018.111
dtk版本：
![1](https://github.com/linuxdeepin/dtk/assets/54758684/cf134335-1e8c-4c75-8a64-bdc265633a2d)

### Minimal Reproducible Case Code | 最小复现案例代码

    DDialog dlg("Test", "This is a test dialog");
    dlg.addButton("Cancel");
    dlg.addButton("Confirm", true, DDialog::ButtonRecommend);

    dlg.clearButtons();
    dlg.exec();

### OBSERVED RESULT | 观察到的结果

![2](https://github.com/linuxdeepin/dtk/assets/54758684/3dc8f9ae-141b-4b2f-969d-b5a1001c900e)

### EXPECTED RESULT | 期望的结果

![3](https://github.com/linuxdeepin/dtk/assets/54758684/10e762c2-953d-4cac-8906-13a5e97037d7)

**Comment by kegechen** [comment]
demo 暂无复现
