### ISSUE TITLE
add dtk documents 

### ISSUE THREAD

**Issue by kegechen** [linuxdeepin/dtk#149]
- [x] #150
- [x] #151
- [x] #152
- [x] #153
- [x] #154
- [x] #155
- [x] #156

输出 `Markdown` 格式文档，可能包含部分源码 `Demo` ，要求不能有错别字，语法错误，源码能编译通过并正常运行

**Comment by kegechen** [comment]
> 领取任务

哪一个？

**Comment by wjyrich** [comment]
> > 领取任务
> 
> 哪一个？

 窗口和对话框介绍

**Comment by Van020530** [comment]
进度、状态指示
