### ISSUE TITLE
DTreeView 折叠时，图标模糊

### ISSUE THREAD

**Issue by Kakueeen** [linuxdeepin/dtk#15]
【前置条件】
分辨率：2560x1600，1.5倍缩放
【结果】
收起时每一组分类下item的图标都会有严重的锯齿

![image](https://user-images.githubusercontent.com/60250462/230590693-0eecb897-f0b0-4678-81e5-e48b34857f45.png)

[bug-193735](https://pms.uniontech.com/bug-view-193735.html)

**Comment by kegechen** [comment]
https://gerrit.uniontech.com/c/base/qtbase-opensource-src/+/210187 
见 pms 描述
