### ISSUE TITLE
RadioButton 的 Text 的 color 未指定

### ISSUE THREAD

**Issue by kegechen** [linuxdeepin/dtk#19]
未指定 Text 的颜色，导致无法跟随主题颜色变化，也和 checkbox 颜色不一致，可以根据设计图调整一下

![image](https://user-images.githubusercontent.com/23466548/218380332-d3cfc1ba-60cf-49a1-89f6-c734fe69c314.png)

**Comment by kegechen** [comment]
bug-179189

**Comment by 18202781743** [comment]
![image](https://github.com/linuxdeepin/dtk/assets/20967670/405422bc-e697-4812-a2ba-8cebd9ad21d1)

**Comment by luodeepin** [comment]
验证通过

![image](https://github.com/linuxdeepin/dtk/assets/96416089/904028ef-e945-4a70-abc5-aa890e261215)

**Comment by 18202781743** [comment]
已经集成过，但issue未关闭，

**Comment by luodeepin** [comment]
验证通过
音乐 7.0.2.80
![image](https://github.com/linuxdeepin/dtk/assets/96416089/709fb1c7-329d-4138-89ff-2e6c206db723)
