### ISSUE TITLE
菜单显示问题

### ISSUE THREAD

**Issue by kegechen** [linuxdeepin/dtk#23]
[期望]
菜单按钮点击即时展示菜单（不需要移动一下鼠标位置才显示），再一次点击菜单隐藏（类似widget中popup菜单）

![image](https://user-images.githubusercontent.com/23466548/219249636-909cd1e7-dfc9-4e9b-a912-87933e812bf0.png)

[bug-173409](https://pms.uniontech.com/bug-view-173409.html)

**Comment by starhcq** [comment]
菜单显示问题在5.6.8-1已修复，但是#121 这个问题依然存在，并且弹出下拉框菜单项图标也不对。
![image](https://user-images.githubusercontent.com/40752904/229402223-10eb19d4-670c-4575-8121-ef5aeb4d354e.png)

**Comment by 18202781743** [comment]
下拉框需要移动鼠标才显示的问题与菜单显示问题相同，但图标问题需要进一步定位，应该是dci图标绘制错误，我这边没有复现，需要核对下包的版本，看下dtkgui和dde-qt5integration，

**Comment by 18202781743** [comment]
问题已经修复，
