### ISSUE TITLE
DStandardItem 设置背景色之后圆角消失

### ISSUE THREAD

**Issue by FeiWang1119** [linuxdeepin/dtk#26]
![image](https://user-images.githubusercontent.com/102005754/229742351-04e207d5-1c5f-4687-a9f7-f520257ae4fa.png)

DStandardItem *item = new DStandardItem("添加指纹");
item->setBackgroundRole(DPalette::TextWarning);

**Comment by 18202781743** [comment]
这以前应该也存在无圆角的背景，
是在DStyledItemDelegate::paint中绘制了PE_PanelItemViewItem，对应的设置了backgroundBrush后，qcommonstyle就会用它填充背景，导致无圆角，
若需要圆角背景，应该在chameleonstyle里对PE_PanelItemViewItem绘制非Select状态

**Comment by 18202781743** [comment]
![image](https://user-images.githubusercontent.com/20967670/229793391-a48ddc79-356f-4c79-aa50-0e8aba016908.png)
