### ISSUE TITLE
dialog 中的 lineedit 失去焦点时背景颜色容易无法区分边框（融入背景）

### ISSUE THREAD

**Issue by kegechen** [linuxdeepin/dtk#31]
[步骤]

1，右键文管标题栏多功能菜单里的设置共享密码；2，鼠标点击弹窗之外的其他地方，使弹窗失去焦点

[结果]

弹窗 **失去焦点** 之后，输入框看不见了

[期望]

弹窗失去焦点之后，输入框只是弱化，不要完全看不见

![企业微信截图_16800549766009](https://user-images.githubusercontent.com/23466548/228407021-3182645a-d029-4104-86d4-a8d46d4159c0.png)

[bug-190119](https://pms.uniontech.com/bug-view-190119.html)

**Comment by kegechen** [comment]
DDialog 是有透明度的，如果后面的窗口是白色会印过来，导致不太容易看清lineedit的背景颜色，看是否降低dialog的透明度，或者微调一下lineedit的背景色

**Comment by kegechen** [comment]
![image](https://user-images.githubusercontent.com/23466548/228494031-935770e2-ffc6-4eda-a9b1-9133fa849af4.png)
修复前 1，2
修复后 3, 4

**Comment by babyfengfjx** [comment]
@luodeepin   验证https://github.com/linuxdeepin/developer-center/issues/4069 问题时，可同步处理该issue。

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230426/deepin-23-beige-amd64-20230426-101953.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial

内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.10
【验证步骤】：问题单中描述的步骤

【验证结果】：测试通过
![g](https://user-images.githubusercontent.com/96416089/235035724-100c206a-f9db-48a6-9e1a-4e49cc281efa.png)
