### ISSUE TITLE
DialogWindow 中的 RecommandButton 样式错误

### ISSUE THREAD

**Issue by kegechen** [linuxdeepin/dtk#43]
![image](https://user-images.githubusercontent.com/23466548/218972483-8d74926a-281e-4baa-928e-348ddbc5af7f.png)

bug-168405

**Comment by kegechen** [comment]
![image](https://user-images.githubusercontent.com/23466548/219237625-ee1a9797-4782-428b-b75d-45a87fbcf64b.png)

**Comment by 18202781743** [comment]
已经处理，bug没有对应的应用issue,
