### ISSUE TITLE
应用浅色暗色主题无法记住

### ISSUE THREAD

**Issue by kegechen** [linuxdeepin/dtk#45]
【操作步骤】： 

打开“音乐”、“看图”、“相册”，主菜单中主题设置为深色
关闭应用，再次打开，观察主题显示                                                               
 --【预期结果】：主题显示为“深色”
【实际结果】：主题显示为“浅色”，打开主菜单-主题，勾选为“跟随系统”，重启应用后主题设置不生效（若系统主题为“深色”，应用中主题设置为“浅色”，重启应用后应主题依然变为“跟随系统”）

[bug-184799](https://pms.uniontech.com/bug-view-184799.html)

**Comment by kegechen** [comment]
https://github.com/linuxdeepin/dtkgui/pull/73

这里还是用了gsettings. 等后续dconfig支持empty id后换成dconfig

**Comment by 18202781743** [comment]
问题已经解决，
