### ISSUE TITLE
V23相册 点击筛选下拉框，不能弹出下拉框菜单项

### ISSUE THREAD

**Issue by starhcq** [linuxdeepin/dtk#48]
[步骤]

1、点击右上角筛选图片/视频按钮

[结果]

1、不能弹出下拉菜单
![file-read-627805](https://user-images.githubusercontent.com/40752904/227899582-db646dc5-aae2-4578-843b-4254adefab04.gif)

[期望]

1、能够弹出下拉框菜单项

[pms](https://pms.uniontech.com/bug-view-193025.html)

**Comment by kegechen** [comment]
可能和 https://github.com/linuxdeepin/dtk/issues/23 这个类似

**Comment by babyfengfjx** [comment]
@kegechen  我看关联的单子说还是有问题，这个问题解决后请同步关联解决的PR，提交集成后，我们反馈到子项目进行复验。
@luodeepin 请优化问题标题，在后期提交集成后，跟进回归验证。

**Comment by kobe337** [comment]
![image](https://github.com/linuxdeepin/dtk/assets/17869922/791dbe65-7c20-4d62-84ef-135b549d05a2)
【验证环境】：v23 beta
镜像：https://cdimage.uniontech.com/community/releases/23-Beta/deepin-desktop-community-23-Beta-amd64.iso
仓库：deb https://community-packages.deepin.com/beige/ beige main commercial community
内核：Linux deepin-PC 6.1.11-amd64-desktop-hwe #23.01.00.14 SMP PREEMPT_DYNAMIC Fri May 12 14:47:29 CST 2023 x86_64 GNU/Linux
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过

**Comment by kobe337** [comment]
拓展验证，切换不同的页面，回到所有项目页面，显示正常，下拉框功能正常
