### ISSUE TITLE
对话框显示dci图标异常

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/dtk#49]
对话框指定productIcon 为 deepin-home，图标引擎查找为dci时显示异常

![image](https://user-images.githubusercontent.com/20967670/230302525-79923615-b5e1-4d9b-98b0-7b62c494b7ad.png)

查找为svg时显示正常

![image](https://user-images.githubusercontent.com/20967670/230303380-5524caa5-fae9-4882-ae0d-4870254e8246.png)

**Comment by SuperEffie** [comment]
【验证环境】
【镜像地址】：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230309/
【集成链接】：[#4050](https://github.com/linuxdeepin/developer-center/issues/4050)
【版本信息】：libdtkdeclarative5包：5.6.9；deepin-home：1.0.20
【验证结论】：问题已修复，深度之家“关于”弹框显示正常
【截图信息】：
![deepin-home](https://user-images.githubusercontent.com/58986464/231370878-794e325d-34c7-4135-a8ff-f84127a6503e.jpg)

**Comment by SuperEffie** [comment]
见以上备注，关闭此issue
