### ISSUE TITLE
标题栏高度设置无法实时生效

### ISSUE THREAD

**Issue by kegechen** [linuxdeepin/dtk#51]
### SUMMARY | 问题概要

前置条件:
1. 升级 dde-dconfig-daemon / dde-dconfi-editor 到最新版本
2. 通过 dde-dconfi-editor 设置标题栏高度.
![image](https://user-images.githubusercontent.com/23466548/232427795-2b5dcc20-2663-4fb8-b697-d2759292c30d.png)

结果:
1. 设置后无法实时生效,关闭应用后再次打开生效
2. 标题栏的阴影位置异常
![image](https://user-images.githubusercontent.com/23466548/232428057-746c0c85-6d21-4fc4-91bf-d3905c4e1638.png)

### DTK and OS VERSIONS | DTK&系统版本信息

dtkcore: master 
dde-app-service: master

### Minimal Reproducible Case Code | 最小复现案例代码

none

**Comment by 18202781743** [comment]
@chenchongbiao

**Comment by chenchongbiao** [comment]
libdtkcore 版本5.6.10
dde-dconfig-daemon / dde-dconfi-editor  版本1.0.20
org.deepin.dtk.ui.preference.json文件安装到了/usr/share/dsg/configs

在dde-dconfig-editor无法读取到配置
![图片](https://user-images.githubusercontent.com/52627687/232958715-31c2f26f-714d-4314-8d26-d0ab006ce3b3.png)

错误提示
"can't not get dbus path for appid=, resource=org.deepin.dtk.ui.preference, subpath=."
"get value handler error for appid=, resource=org.deepin.dtk.ui.preference, subpath=."
@kegechen

**Comment by chenchongbiao** [comment]
> libdtkcore 版本5.6.10 dde-dconfig-daemon / dde-dconfi-editor 版本1.0.20 org.deepin.dtk.ui.preference.json文件安装到了/usr/share/dsg/configs
> 
> 在dde-dconfig-editor无法读取到配置 ![图片](https://user-images.githubusercontent.com/52627687/232958715-31c2f26f-714d-4314-8d26-d0ab006ce3b3.png)
> 
> 错误提示 "can't not get dbus path for appid=, resource=org.deepin.dtk.ui.preference, subpath=." "get value handler error for appid=, resource=org.deepin.dtk.ui.preference, subpath=." @kegechen

好了 新装的dde-dconfig-daemon没重启
