### ISSUE TITLE
【任务栏】单击声音图标，双击 输出设备名称时，重命名的图框显示重叠

### ISSUE THREAD

**Issue by tsic404** [linuxdeepin/dtk#55]
### SUMMARY | 问题概要

单击声音图标，双击 输出设备名称时，重命名的图框显示重叠

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

内核 Linux v233-PC 5.18.17-amd64-desktop-hwe linuxdeepin/developer-center#23.01.00.06 SMP PREEMPT_DYNAMIC Mon Oct 31 17:25:49 CST 2022 x86_64 GNU/Linux
 任务栏   6.0.9.2 

### STEPS TO REPRODUCE | 复现步骤

1. 鼠标放置到任务栏的声音图标上，单击鼠标左键打开声音面板
2. 双击 输出设备名称 

### OBSERVED RESULT | 观察到的结果

重命名的图框显示重叠
![file-read-598531](https://user-images.githubusercontent.com/48748112/219579638-d154a9ce-6858-4a85-8728-0fca6aaecbed.gif)

### EXPECTED RESULT | 期望的结果

输出设备名称框显示正常

**Comment by vivianxf** [comment]
验证镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso
验证版本：dde-dock：6.0.9.2
验证步骤：提单的步骤
验证现象：符合预期
验证结果：通过

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/community/releases/23-Alpha2/deepin-desktop-community-23-Alpha2-amd64.iso

仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
     deb https://community-packages.deepin.com/beige/ beige main commercial community
包版本：dde-dock       6.0.12  
       dde-control-center 6.0.11-1
内核：Linux v23-PC 6.1.11-amd64-desktop-hwe linuxdeepin/developer-center#23.01.00.01 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux
【验证步骤】：问题单中描述的步骤

【验证结果】：不通过
![录屏_dde-desktop_20230418155048](https://user-images.githubusercontent.com/96416089/232710946-6ed5bb2e-2b16-46c1-958d-9f03b5fa2b10.gif)

**Comment by tsic404** [comment]
新的 dock popupwidget 采用了DBlurEffectWidget, DListView的item进行编辑时，QLineEditor会没有背景，显示item和QLineEditor两份。

**Comment by tsic404** [comment]
[demo-test.zip](https://github.com/linuxdeepin/developer-center/files/11283899/demo-test.zip)
使用DBlurEffectWidget 加上DListView的demo，效果是一样的。

**Comment by 18202781743** [comment]
只有当BlurEffectWidget为顶层窗口时，会出现这个问题，
将 以上[demo-test.zip](https://github.com/linuxdeepin/developer-center/files/11283899/demo-test.zip)
main.cpp 改为以下 就不会出现，主要是 `setParent`
```c++
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    MyWidget myWidget(nullptr);
    myWidget.show();
    QWidget widget;
    myWidget.setParent(&widget);
    widget.resize(QSize(400, 400));
    widget.show();
    return app.exec();
}
```

**Comment by asterwyx** [comment]
该问题由提交https://github.com/linuxdeepin/qt5integration/commit/7638f08063bef7a028a18d3aaab75bcef531d1e0 引起，createEditor创建的lineedit在DBlurEffectWidget等透明窗口下会变得透明，导致下面绘制的text显示出来。@kegechen 正在沟通解决方案。

**Comment by kegechen** [comment]
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/linuxdeepin:/qt5integration:/PR-152/deepin_develop/ ./
@babyfengfjx 相同问题还有 https://github.com/linuxdeepin/developer-center/issues/4069

**Comment by babyfengfjx** [comment]
@luodeepin  请使用上述仓库开展回归验证。

**Comment by kegechen** [comment]
> deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/linuxdeepin:/qt5integration:/PR-152/deepin_develop/ ./ @babyfengfjx 相同问题还有 [linuxdeepin/developer-center#4069](https://github.com/linuxdeepin/developer-center/issues/4069)

qtbase-abi-5-15-7 版本:
deb [trusted=yes] https://ci.deepin.com/repo/obs/home:/chenke:/dtk/Deepin_23_stable-commercial/ ./

**Comment by luodeepin** [comment]
【验证环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230426/deepin-23-beige-amd64-20230426-101953.iso
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/stable/ beige main community commercial
deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial

内核：Linux v23-PC 6.1.11-amd64-desktop-hwe #23.01.00.10
【验证步骤】：问题单中描述的步骤

【验证结果】：通过
![录屏_选择区域_20230428100218](https://user-images.githubusercontent.com/96416089/235036832-11aa9a9b-0fef-44e4-a506-e947a58e3c44.gif)
