### ISSUE TITLE
DDialog 设置disable后再次enable后关闭按钮依然是disable状态

### ISSUE THREAD

**Issue by Decodetalkers** [linuxdeepin/dtk#59]
### DTK and OS VERSIONS | DTK&系统版本信息

dtkwidget 5.6.9

### Minimal Reproducible Case Code | 最小复现案例代码

```cpp
QPushButton *btn = new QPushButton;

connect(btn, &QPushButton::clicked, this, [ ]{
    DDialog dialog;
    dialog.setDisabled(true);
    QTimer::singleShot(1000, [&dialog] {
        dialog.setDisabled(false);
   })
   dialog.exec()
});
```

### OBSERVED RESULT | 观察到的结果

设置disable后再次enable后关闭按钮无法使用

**Comment by FeiWang1119** [comment]
父对象disable, 子对象一定disable。父对象enable，子对象不一定enable.

**Comment by asterwyx** [comment]
https://github.com/linuxdeepin/dtkwidget/pull/460

**Comment by asterwyx** [comment]
https://github.com/linuxdeepin/developer-center/issues/4757

**Comment by kobe337** [comment]
验证通过，包名为libdtkwidget5


![Image](https://github.com/linuxdeepin/dtk/assets/17869922/9c01292d-cf01-4b9c-a24f-3a75a0ca6045)

**Comment by kobe337** [comment]
RC发布版本验证通过关闭
![rctg](https://github.com/linuxdeepin/dtk/assets/17869922/928521a5-c428-4947-9bb3-1fe0918138d9)
