### ISSUE TITLE
【deepin_V23_beta】【一般】【紧急】【集成测试】【终端】系统主题设置为浅色,终端主题设置为深色时,开启终端后标题栏与工作区主题展示不一致

### ISSUE THREAD

**Issue by xuqi27837288** [linuxdeepin/dtk#60]
### SUMMARY | 问题概要

必现问题

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
镜像地址：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230424
内核信息: Linux test-PC 6.1.11-amd64-desktop-hwe linuxdeepin/developer-center#23 SMP PREEMPT_DYNAMIC Mon Feb 27 17:25:36 CST 2023 x86_64 GNU/Linux

终端:6.0.5+rb1
```

### PRE-REQUIREMENT | 预置条件

1、系统主题设置为浅色
2、终端主题设置为深色

### STEPS TO REPRODUCE | 复现步骤

1、使用快捷键重新打开终端，观察终端的样式展示效果

### OBSERVED RESULT | 观察到的结果

1、终端标题栏展示为浅色，工作区展示为深色

https://user-images.githubusercontent.com/62528742/234157599-c8253a33-fd02-471e-b32d-73f5c5b208d6.mp4

### EXPECTED RESULT | 期望的结果

1、终端标题栏与工作区展示主题颜色为深色

**Comment by babyfengfjx** [comment]
@ArchieMeng  请帮忙优化~

**Comment by asterwyx** [comment]
@babyfengfjx  dtkgui已经提交修复此问题：https://github.com/linuxdeepin/dtkgui/pull/150 请验证

**Comment by xuqi27837288** [comment]
@asterwyx 麻烦帮忙关联一下提交的相关集成，稍后我将添加集成仓库进行验证~

**Comment by asterwyx** [comment]
@18202781743

**Comment by xuqi27837288** [comment]
update

**Comment by xuqi27837288** [comment]
【验证环境】：v23 0516镜像
镜像：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516
仓库：deb https://ci.deepin.com/repo/deepin/deepin-community/testing/ unstable main dde community commercial
内核：Linux test-PC 6.1.11-amd64-desktop-hwe
【验证步骤】：问题单中描述的步骤
【验证结果】：回归测试通过

**Comment by babyfengfjx** [comment]
问题已经解决。
