### ISSUE TITLE
【UI】dcombox输入框鼠标hover的响应范围错误

### ISSUE THREAD

**Issue by pppanghu77** [linuxdeepin/dtk#61]
### SUMMARY | 问题概要

输入框没有状态改变，下拉按钮变为了hover状态

### DTK VERSIONS | DTK版本信息

dtkwidget 5.6.9

### OBSERVED RESULT | 观察到的效果

输入框没有状态改变，下拉按钮变为了hover状态

### EXPECTED RESULT | 期望的设计效果

鼠标hover的地方出现响应即可，不要出现不相关的响应

**Comment by 18202781743** [comment]
更新 dde-qt5integration包，重启对应应用，例如 日历（日历为玲珑应用，需要更新玲珑的dtk包，而非单纯的dde-qt5integration包）
![image](https://github.com/linuxdeepin/dtk/assets/20967670/268ed4b4-c686-4b09-8a4a-9d0f9daf9421)

**Comment by 18202781743** [comment]
可以寻找其它使用combobox的非玲珑应用，

**Comment by 18202781743** [comment]
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-206/testing/ ./

**Comment by 18202781743** [comment]
dde-printer应用可以作为测试，

![image](https://github.com/linuxdeepin/dtk/assets/20967670/ae4154cc-04b5-4203-a1af-e9762003e7df)


![image](https://github.com/linuxdeepin/dtk/assets/20967670/21061ed3-32dd-4dcc-b11e-abba5467e1b5)

**Comment by kobe337** [comment]
验证通过

![Image](https://github.com/linuxdeepin/dtk/assets/17869922/f67cd9b9-b795-4d62-bab7-3c5b6f89dacc)

**Comment by 18202781743** [comment]
已经测试过，应该可以关闭了，

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230908/deepin-23-beige-beta2-amd64-20230908-160331.iso

【结论】：
回归测试通过，暂无严重问题及影响
