### ISSUE TITLE
dtk控件，关于弹框中多了“版本”字段

### ISSUE THREAD

**Issue by beier11** [linuxdeepin/dtk#62]
### SUMMARY | 问题概要

dtk控件，关于弹框中多了“版本”字段
本来应该是
版本
xxx

结果成了
版本
版本：xxx

### DTK and OS VERSIONS | DTK&系统版本信息

dtkcore 5.6.8

### Minimal Reproducible Case Code | 最小复现案例代码

本来应该是
版本
xxx

结果成了
版本
版本：xxx

### OBSERVED RESULT | 观察到的结果

本来应该是
版本
xxx

结果成了
版本
版本：xxx

### EXPECTED RESULT | 期望的结果

版本
xxx

### ADDITIONAL INFORMATION | 额外补充

BUG 197931

**Comment by FeiWang1119** [comment]
![image](https://user-images.githubusercontent.com/102005754/234187453-2c33a366-6a5a-410f-a3aa-11b6e6628398.png)
