### ISSUE TITLE
通过 new 创建DFileDialog对象exec模态显示后，调用close函数后造成mainwindow主窗口无法鼠标拖动

### ISSUE THREAD

**Issue by ldz-uniontech** [linuxdeepin/dtk#64]
### SUMMARY | 问题概要

原始bug：https://pms.uniontech.com/bug-view-183603.html ，未解决完整。
通过new 一个DFiledialog,调用exec()，再别处主动调用close()，DFiledialog 窗口显示关闭，但会造成主窗口鼠标无法拖动

### DTK and OS VERSIONS | DTK&系统版本信息

deepin v20  qt5integration-5.6.9

### Minimal Reproducible Case Code | 最小复现案例代码

#ifndef DTKMAINWINDOW_H
#define DTKMAINWINDOW_H

#include <QMainWindow>
#include <DMainWindow>
#include <QFileDialog>

DWIDGET_USE_NAMESPACE
class dtkMainWindow : public DMainWindow
{
    Q_OBJECT
public:
    explicit dtkMainWindow(QWidget *parent = nullptr);
    ~dtkMainWindow();
signals:

public slots:
    void onOpenFileDialog();
private:
    QFileDialog *m_pNewFileDlg = nullptr;
};

#endif // DTKMAINWINDOW_H

#include "dtkmainwindow.h"
#include <QPushButton>
#include <QTimer>
dtkMainWindow::dtkMainWindow(QWidget *parent) : DMainWindow(parent)
{
    QPushButton *pBtn = new QPushButton("openfiledlg", this);
    connect(pBtn, &QPushButton::clicked, this, &dtkMainWindow::onOpenFileDialog);
    setCentralWidget(pBtn);
    setFixedSize(300, 150);
}

dtkMainWindow::~dtkMainWindow()
{
}

void dtkMainWindow::onOpenFileDialog()
{
    m_pNewFileDlg = new QFileDialog(this);
    QTimer::singleShot(1000 * 10, this, [ = ]() {
        m_pNewFileDlg->close();
        //m_pNewFileDlg->deleteLater();
    });
    m_pNewFileDlg->exec();
}

### OBSERVED RESULT | 观察到的结果

通过new 一个DFiledialog,调用exec()，再别处主动调用close()，DFiledialog 窗口显示关闭，但会造成主窗口鼠标无法拖动。
最新分析如下：
DFiledialg : QFileDialog : QDialog :QWidget

                             |
                             ----->platformHelper
                                    |
                                    ---Dbus--->Native DFileDialog (文官实现）

 1. 
 DFiledialg* plg = new DFiledialg()
  QTimer::singleShot(15000,this,[plg]() {
        plg->close();
  });
 plg->exec();

 流程：当定时器到时候出发close事件
 QDialog对象重写了closeevent
void QDialog::closeEvent(QCloseEvent *e)
{
#if QT_CONFIG(whatsthis)
    if (isModal() && QWhatsThis::inWhatsThisMode())
        QWhatsThis::leaveWhatsThisMode();
#endif
    if (isVisible()) {
        QPointer<QObject> that = this;
        reject();
        if (that && isVisible())
            e->ignore();
    } else {
        e->accept();
    }
}

#0  QDeepinFileDialogHelper::hide() (this=0x8b3910) at qdeepinfiledialoghelper.cpp:244
#1  0x00007ffff77f12f5 in QDialogPrivate::setNativeDialogVisible(bool) (this=this@entry=0x54a510, visible=visible@entry=false) at dialogs/qdialog.cpp:201
#2  0x00007ffff7803ce7 in QFileDialog::setVisible(bool) (this=0x8c4c40, visible=<optimized out>) at dialogs/qfiledialog.cpp:885
#3  0x00007ffff77f15dd in QDialogPrivate::hide(int) (this=this@entry=0x54a510, resultCode=resultCode@entry=0) at dialogs/qdialog.cpp:158
#4  0x00007ffff77f1614 in QDialog::done(int) (this=this@entry=0x8c4c40, r=0) at dialogs/qdialog.cpp:637
#5  0x00007ffff7801282 in QFileDialog::done(int) (this=0x8c4c40, result=<optimized out>) at dialogs/qfiledialog.cpp:2798
#6  0x00007ffff77f0fd2 in QDialog::closeEvent(QCloseEvent*) (e=0x7fffffffbc90, this=0x8c4c40) at dialogs/qdialog.cpp:748
#7  QDialog::closeEvent(QCloseEvent*) (this=0x8c4c40, e=0x7fffffffbc90) at dialogs/qdialog.cpp:740

void QDeepinFileDialogHelper::hide()
{
    ensureDialog();

    if (filedlgInterface)
        filedlgInterface->hide();
.....
}

文官实现
void DFileDialogHandle::hide()
{
    D_D(DFileDialogHandle);

    d->dialog->hide();
}

其实根本原因就是Dfiledialog/QFileDialgo在使用nativedialog的情况下它自己的closeevent没法透传给
nativedialog，因为基类QDialog对于closeevent是如果对话框可见是说明使用者主动调用了close，默认为reject
。但这个行为通过dbus实现的native dialog是不知道的

所以正确的修复方法应该文官的native dailog dbus代理
void DFileDialogHandle::hide()
{
    D_D(DFileDialogHandle);

    //本地文官框在hide调用前可见说明是用户主动调用close来关闭QfileDialg则调用native的对话框reject结束platformhelp的loop即可
    if (d->dialog->isVisible()) {
        d->dialog->reject();
    }

### EXPECTED RESULT | 期望的结果

对应DFiledialog对话框对象在主动调用close()后，对象能正常关闭退出不阻塞事件循环，不影响主窗口的鼠标拖动

**Comment by asterwyx** [comment]
https://github.com/linuxdeepin/qt5integration/pull/155

**Comment by asterwyx** [comment]
集成 https://github.com/linuxdeepin/developer-center/issues/4309 已包含，如无问题请求关闭issue。 @babyfengfjx

**Comment by xuqi27837288** [comment]
已集成修复该问题~问题单回归关闭 ~
