### ISSUE TITLE
dtk应用弹出的文件选择框 与应用未建立父子关系

### ISSUE THREAD

**Issue by zy-seven** [linuxdeepin/dtk#65]
### SUMMARY | 问题概要

应用唤起文管的窗口后，再点击应用，文件选择框会显示到应用下面，文管窗口不应被点至下一层级

pms：https://pms.uniontech.com/bug-view-197415.html

### DTK and OS VERSIONS | DTK&系统版本信息

uos: 1060
dtk:5.6.6

### Minimal Reproducible Case Code | 最小复现案例代码

系统自带dtk应用

**Comment by 18202781743** [comment]
已经修复了，https://github.com/linuxdeepin/qt5integration/pull/157
