### ISSUE TITLE
dtk应用调起的文件选择框 窗口属性transientfor 未设置父窗口id，所以选择框未与应用建立父子关系

### ISSUE THREAD

**Issue by beier11** [linuxdeepin/dtk#67]
### SUMMARY | 问题概要

dtk应用调起的文件选择框 窗口属性transientfor 未设置父窗口id，所以选择框未与应用建立父子关系

### DTK and OS VERSIONS | DTK&系统版本信息

BUG 197415

### Minimal Reproducible Case Code | 最小复现案例代码

BUG 197415

**Comment by kegechen** [comment]
Repeated Issue #65
