### ISSUE TITLE
wayland模式，控制中心窗口无二分屏入口

### ISSUE THREAD

**Issue by beier11** [linuxdeepin/dtk#68]
### SUMMARY | 问题概要

wayland模式，控制中心窗口无二分屏入口
[前置条件]：1、wayland协议；
[步骤]
1、切换到wayland模式，点击控制中心/终端-鼠标移至最大化窗口上-查看是否有二分屏入口
[结果]
1、没有二分屏入口

### DTK and OS VERSIONS | DTK&系统版本信息

https://cdimage.uniontech.com/daily-iso/1060/professional/daily-stable/20230316-stable/report/packages-log/packagelist_professional_amd64.txt

### Minimal Reproducible Case Code | 最小复现案例代码

https://pms.uniontech.com/bug-view-193985.html

### OBSERVED RESULT | 观察到的结果

没有二分屏入口

### EXPECTED RESULT | 期望的结果

切换到wayland模式，点击控制中心/终端-鼠标移至最大化窗口上-有二分屏入口

### ADDITIONAL INFORMATION | 额外补充

https://pms.uniontech.com/bug-view-193985.html

**Comment by 18202781743** [comment]
讨论后定为非问题，
此问题在1060上复现，原因是代码cp问题，分屏功能需要改动是v23，此问题在1060上，原因是仓库里没有dwayland包，导致未调用服务，

```QT_LOGGING_RULES="dtk*.debug=true" deepin-editor ```， 可以看到相关警告的日志 `This package is not compiled as dwayland, and [ `
1060上单独revert了此功能代码来修复此问题，
