### ISSUE TITLE
对话框标题栏存在撕裂阴影

### ISSUE THREAD

**Issue by 18202781743** [linuxdeepin/dtk#69]
### SUMMARY | 问题概要

AboutDialog设置了 maximumWidth: 360， 这个值小于内部设置的width，在InWindowBlur的阴影就会出现问题，

### DTK and OS VERSIONS | DTK&系统版本信息

libdtkdeclarative5: all

### Minimal Reproducible Case Code | 最小复现案例代码

`dtkdeclarative`中的`qml-inspect`应用
```qml
TitleBar {
    aboutDialog: AboutDialog {
        maximumWidth: 400
    }
}
```

### OBSERVED RESULT | 观察到的结果

![image](https://user-images.githubusercontent.com/20967670/236617991-b0a24d6a-4b8f-4674-947a-750c51b649e1.png)

**Comment by myml** [comment]
已修复，因为这是一个依赖库，需要使用另外的应用进行测试，我改了deepin-home来触发这个bug
测试流程：
先添加deepin-home的测试仓库 https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-197/testing/
安装这个能触发bug的深度之家，安装后打开深度之家的关于对话框能看到bug
![图片](https://github.com/linuxdeepin/dtkdeclarative/assets/13045857/7704752e-635a-4894-bae6-d57b6be7554b)

然后在添加dtk的测试仓库 https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-193/testing/
安装 libdtkdeclarative5 后再重启深度之家查看修复的效果

**Comment by SuperEffie** [comment]
【镜像地址】：https://packagesupdate.uniontech.com/repo/uos-professional/image-beige/CUSTOM/lichenggang/20230516/
【版本信息】： libdtkdeclarative5：5.6.13
【验证结论】：验证通过
【截图信息】：
未修复前：
![修复前](https://github.com/linuxdeepin/dtk/assets/58986464/88aed782-6cff-4c12-be2c-64c423375666)
修复后：
![修复后](https://github.com/linuxdeepin/dtk/assets/58986464/a0f7bf56-9091-4cdc-b203-c4d78e9cff70)

**Comment by 18202781743** [comment]
此问题需要继续跟进，对应出现的应用问题  https://github.com/linuxdeepin/developer-center/issues/4222  只是规避掉了，

**Comment by 18202781743** [comment]
应该是这个修复了

https://github.com/linuxdeepin/dtkdeclarative/pull/269/commits/37440ecc8a44e5ee1556f1f94bb56cc7f915d739
