### ISSUE TITLE
search输入框图标显示很小

### ISSUE THREAD

**Issue by iCancely** [linuxdeepin/dtk#72]
### SUMMARY | 问题概要

问题：
控制中心、菜单启动器、全屏启动器中，
顶部搜索框未激活状态时，搜索图标显示偏小，激活后搜索图标显示为正常大小。

### DTK VERSIONS | DTK版本信息

libdtkwidget5 5.6.11
libdtkgui5 5.6.8
dde-qt5integration 5.6.11

### OBSERVED RESULT | 观察到的效果

<img width="860" alt="image" src="https://github.com/linuxdeepin/dtk/assets/111953898/ffeec498-3379-4341-9fba-64079090a230">

### EXPECTED RESULT | 期望的设计效果

激活与未激活状态时，搜索图标的大小显示一样。
<img width="1305" alt="image" src="https://github.com/linuxdeepin/dtk/assets/111953898/b81514a6-92f2-41d0-bfb3-c8c8161dcc1b">

**Comment by 18202781743** [comment]
`libdtkgui5`的图标修改在此提交 `0faedd5009260e015e3a752555675fb498d02e19` ， 版本大于`5.6.8`

**Comment by 18202781743** [comment]
dde-launcher搜索框是自定义了icon，这个icon大小在dtkwidget的DSearchEdit控制，但icon本身有margin,导致显示变小。
![image](https://github.com/linuxdeepin/dtk/assets/20967670/e14d049b-c2cb-4f05-8efa-505213c3baf9)
