### ISSUE TITLE
DListView悬浮和选中的item高度不同

### ISSUE THREAD

**Issue by iCancely** [linuxdeepin/dtk#73]
### SUMMARY | 问题概要

1.打开控制中心
2.选中一个列表，鼠标再悬浮到一个列表上

 结果：
item高度不一致，选中的为46px，鼠标悬浮的为48px
（可以看到选中的与悬浮的中间空了一个像素）

### OBSERVED RESULT | 观察到的效果

<img width="500" alt="image" src="https://github.com/linuxdeepin/dtk/assets/111953898/4f5dcae4-7139-4840-9ecb-e00784bca10d">

### EXPECTED RESULT | 期望的设计效果

选中和悬浮一样的宽度。以控制中心为例那就是48

**Comment by 18202781743** [comment]
deb [trusted=yes] https://ci.deepin.com/repo/obs/deepin:/CI:/TestingIntegration:/test-integration-pr-201/testing/ ./

**Comment by 18202781743** [comment]
更新 dde-qt5integration包， 然后重启控制中心

**Comment by kobe337** [comment]
验证通过


![Image](https://github.com/linuxdeepin/dtk/assets/17869922/bff85bae-8246-41dc-acf7-134059d01f8a)
