### ISSUE TITLE
锁屏界面，音频或视频的快捷按钮部分显示不全

### ISSUE THREAD

**Issue by beier11** [linuxdeepin/dtk#77]
### SUMMARY | 问题概要

[前置条件]

打开 音乐应用，或影院应用

[步骤]

1. 再进入锁屏界面，观察底部音频或视频的快捷图标按钮展示

2. 点击按钮，观察选中态效果展示

[结果]

最右侧的下一首按钮 显示不全，且选中态按钮底部展示不全

### DTK and OS VERSIONS | DTK&系统版本信息

问题版本：libdtkwidget5=5.6.11-1

正常版本：libdtkwidget5 <= 5.6.9.2-1

### Minimal Reproducible Case Code | 最小复现案例代码

问题版本：libdtkwidget5=5.6.11-1

正常版本：libdtkwidget5 <= 5.6.9.2-1

### OBSERVED RESULT | 观察到的结果

最右侧的下一首按钮 显示不全，且选中态按钮底部展示不全

### EXPECTED RESULT | 期望的结果

所有快捷按钮（选中态）显示完整，能正常操作

### ADDITIONAL INFORMATION | 额外补充

libdtkwidget5 新版本引入的问题
https://pms.uniontech.com/bug-view-200781.html

**Comment by kegechen** [comment]
根据设计要求，媒体播放控件是一个固定大小的组合控件，请放在布局器里，参考最新的dde-session-shell。https://github.com/linuxdeepin/dde-session-shell/commit/697efe18ef65254a985001b4b801fec26ee90728
