### ISSUE TITLE
DPushButton深色模式样式错误

### ISSUE THREAD

**Issue by iCancely** [linuxdeepin/dtk#82]
### SUMMARY | 问题概要

深色模式下
1.DPushButton，目前是hover颜色比normal更深（带有主题色的高亮按钮hover也是）
2.DSuggestButton、warningbutton也是一样的问题。

### DTK VERSIONS | DTK版本信息

uos 1060
libdtkgui5 5.6.8
libdtkwidget5 5.6.9.2
dde-qt5integration 5.6.9

### OBSERVED RESULT | 观察到的效果

<img width="2120" alt="image" src="https://github.com/linuxdeepin/dtk/assets/111953898/aef82f66-5f46-4c61-84c4-fe4003dda24c">

### EXPECTED RESULT | 期望的设计效果

正确为：
深色模式下，按钮的hover颜色都会比normal颜色要浅一点。

<img width="1617" alt="image" src="https://github.com/linuxdeepin/dtk/assets/111953898/d34a42fe-a861-4c36-97a7-abe6d44d1b7e">

**Comment by kobe337** [comment]
验证通过
包名：libdtkwidget5


![Image](https://github.com/linuxdeepin/dtk/assets/17869922/fd77eaab-1e99-4174-a65a-0dd1fb71ebce)

**Comment by kobe337** [comment]
【环境】：
镜像：https://cdimage.uniontech.com/daily-iso/image-beige/CUSTOM/lichenggang/20230908/deepin-23-beige-beta2-amd64-20230908-160331.iso
组件版本：libdtkwidget5 ：5.6.16
【结论】：
回归测试通过，暂无严重问题及影响

**Comment by kobe337** [comment]
验证通过关闭
