### ISSUE TITLE
DLineEdit放到DDialog中setAlert没有效果

### ISSUE THREAD

**Issue by 15190487506** [linuxdeepin/dtk#91]
### SUMMARY | 问题概要

DLineEdit放到DDialog中setAlert没有效果
[test.zip](https://github.com/linuxdeepin/dtk/files/11768458/test.zip)

### DTK VERSIONS | DTK版本信息

dtkwidget: 5.6.10

### OBSERVED RESULT | 观察到的效果

设置setAlert(true),DLineEdit背景没有变化

**Comment by kegechen** [comment]
类似问题 https://github.com/linuxdeepin/dtk/issues/31
为了解决lineedit在透明窗口上显示的问题，透明窗口上的lineedit绘制可能不会用调色板中的 button颜色。而是透明色

**Comment by kegechen** [comment]
如果设置过palette就不再使用透明色了
