### ISSUE TITLE
DSearchEdit 居左图标深色主题没有适配，居中图标太小

### ISSUE THREAD

**Issue by 15190487506** [linuxdeepin/dtk#97]
### SUMMARY | 问题概要

DSearchEdit 居左图标深色主题没有适配，居中图标太小
![image](https://github.com/linuxdeepin/dtk/assets/78856607/48a5a53b-d0b2-499c-a823-b6c6ddfa7920)
![image](https://github.com/linuxdeepin/dtk/assets/78856607/da06ffa3-9b27-4767-a456-112a495d5ffc)

### DTK and OS VERSIONS | DTK&系统版本信息

dtkwidget:5.6.11.5

### Minimal Reproducible Case Code | 最小复现案例代码

1

**Comment by kegechen** [comment]
dtkgui >= 5.6.9 && dtkwidget >= 5.6.9

**Comment by kegechen** [comment]
图标没有跟随的原因是action的图标改成了内置图标，绘制时没有使用builtiniconengine的绘制，只是获取了pixmap自己绘制的。没有用到填充颜色的机制。

**Comment by kegechen** [comment]
见这个 https://github.com/linuxdeepin/dtk/issues/37 
主要的修复在这三个提交，如果漏掉了可能会达不到理想效果

- https://github.com/linuxdeepin/dtkgui/pull/138
- https://github.com/linuxdeepin/dtkwidget/pull/377
- https://github.com/linuxdeepin/qt5integration/pull/132


dtkgui >= 5.6.9
dtkwidget > 5.6.9
qt5integration >= 5.6.9
qt5base-dev > 5.15 (or add-setting-thc-ICON-size-attribute-in-lineedit-to-the-style-plugin.patch)
